// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fBsca94bet4EUSoXHGArJn
// Component: Qz-_Gd5GGj46I
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: fBsca94bet4EUSoXHGArJn/projectcss
import * as sty from "./PlasmicLogoCloudSection2.module.css"; // plasmic-import: Qz-_Gd5GGj46I/css
import loomsvg2ZAmnIqdyg4D4A from "./images/loomsvg2.svg"; // plasmic-import: zAMNIqdyg4D4a/picture
import strapisvg2Z5QamJbWe0Wip from "./images/strapisvg2.svg"; // plasmic-import: z5QamJBWe0Wip/picture
import segmentsvg2FwOkXLzE6LgVt from "./images/segmentsvg2.svg"; // plasmic-import: FWOkXLzE6lgVt/picture
import xstate1SvgLxgOn1MklUcd from "./images/xstate1Svg.svg"; // plasmic-import: lxgON1mklUCD-/picture
import mapboxsvg2Brxd3IEuiOfky from "./images/mapboxsvg2.svg"; // plasmic-import: BRXD3iEUIOfky/picture

export const PlasmicLogoCloudSection2__VariantProps = new Array();

export const PlasmicLogoCloudSection2__ArgProps = new Array("children");

function PlasmicLogoCloudSection2__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__nGexs)}
                role={"img"}
                src={loomsvg2ZAmnIqdyg4D4A}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__vTyB8)}
                role={"img"}
                src={strapisvg2Z5QamJbWe0Wip}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img___1AK4S)}
                role={"img"}
                src={segmentsvg2FwOkXLzE6LgVt}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__tXovc)}
                role={"img"}
                src={xstate1SvgLxgOn1MklUcd}
              />

              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__sdqKc)}
                role={"img"}
                src={mapboxsvg2Brxd3IEuiOfky}
              />
            </React.Fragment>
          ),

          value: args.children
        })}
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLogoCloudSection2__ArgProps,
      internalVariantPropNames: PlasmicLogoCloudSection2__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicLogoCloudSection2__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLogoCloudSection2";
  } else {
    func.displayName = `PlasmicLogoCloudSection2.${nodeName}`;
  }
  return func;
}

export const PlasmicLogoCloudSection2 = Object.assign(
  // Top-level PlasmicLogoCloudSection2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    // Metadata about props expected for PlasmicLogoCloudSection2
    internalVariantProps: PlasmicLogoCloudSection2__VariantProps,
    internalArgProps: PlasmicLogoCloudSection2__ArgProps
  }
);

export default PlasmicLogoCloudSection2;
/* prettier-ignore-end */
