// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fBsca94bet4EUSoXHGArJn
// Component: wKR4CMkcsbgp2
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import HeroSection2 from "../../HeroSection2"; // plasmic-import: LVBcC2YtkKzbp/component
import Button from "../../Button"; // plasmic-import: lukbyibyAwqNS/component
import Divider from "../../Divider"; // plasmic-import: pORI5sApnRrOD/component
import Textinput from "../../Textinput"; // plasmic-import: nKovcSFqQPKzk/component
import Navigation from "../../Navigation"; // plasmic-import: pNv5KU4sb2jMa/component
import ValuesSection3 from "../../ValuesSection3"; // plasmic-import: vJC7mZ5RBiPCQ/component
import Valueprop from "../../Valueprop"; // plasmic-import: b5qPoGVcjzfiH/component
import ValuesSection2Dark from "../../ValuesSection2Dark"; // plasmic-import: llPcXwSuWZliV/component
import PricingSection3 from "../../PricingSection3"; // plasmic-import: 7jlHC-LjyiARC/component
import ShopBanners from "../../ShopBanners"; // plasmic-import: iwLFdIiajJGZ6/component
import Banner from "../../Banner"; // plasmic-import: rFx_o2QGdlilY/component
import LogoCloudSection2 from "../../LogoCloudSection2"; // plasmic-import: Qz-_Gd5GGj46I/component
import TestimonialsSection1 from "../../TestimonialsSection1"; // plasmic-import: d5U8HfpcPZ-4L/component
import Testimonial from "../../Testimonial"; // plasmic-import: 8jPKTuirLdl_6/component
import CallToActionSection1 from "../../CallToActionSection1"; // plasmic-import: Nx70f4NxK5_lw/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: AmNFVTFTh6UY0/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: fBsca94bet4EUSoXHGArJn/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: wKR4CMkcsbgp2/css
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: 1Zh4qskDqfOaZ/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: oeVLLou_u7G94/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: 5CFx7tW3uTLU2/icon
import image13FVFz0AkEbu1W6 from "./images/image13.svg"; // plasmic-import: fVFz0AkEbu1W6/picture

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <HeroSection2
            data-plasmic-name={"heroSection2"}
            data-plasmic-override={overrides.heroSection2}
            className={classNames("__wab_instance", sty.heroSection2)}
            foreground={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox__dbum7)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__nrrVr)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__odIkY)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__zMXb
                        )}
                      >
                        {"Updated!"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__mF4BQ
                      )}
                    >
                      <span>
                        <React.Fragment>{"Designs that "}</React.Fragment>
                        <span style={{ textDecoration: "underline" }}>
                          {"adapt"}
                        </span>
                      </span>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__nu7Ww
                      )}
                    >
                      {
                        "Orci dui condimentum rutrum laoreet hac purus porta sem sem a vivamus a posuere vel molestie."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__zXpQw)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__t4HwH
                      )}
                      darkGray={"darkGray"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__wD7Mf
                          )}
                        >
                          {"Start now ->"}
                        </div>
                      }
                    />

                    <Button
                      bgDifference={"bgDifference"}
                      className={classNames(
                        "__wab_instance",
                        sty.button__tiYu4
                      )}
                      darkGray={"darkGray"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__ncruU
                          )}
                        >
                          {"Learn more…"}
                        </div>
                      }
                    />
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.freeBox___0Phvv)}
                >
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__t4Xz4)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__m6G8F)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__k1FpT
                        )}
                      >
                        {"Sign up with"}
                      </div>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox___3EwRj
                        )}
                      >
                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__asQco
                          )}
                          ouline={"ouline"}
                          slot={"Apple"}
                          startIcon={"startIcon"}
                        />

                        <Button
                          className={classNames(
                            "__wab_instance",
                            sty.button__hHVe2
                          )}
                          ouline={"ouline"}
                          slot={"Google"}
                          startIcon={"startIcon"}
                        >
                          <Icon6Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__r3TeC
                            )}
                            role={"img"}
                          />
                        </Button>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__opywm
                        )}
                      >
                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider__hZqF8
                          )}
                        />

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__ejb5H
                          )}
                        >
                          {"Or"}
                        </div>

                        <Divider
                          className={classNames(
                            "__wab_instance",
                            sty.divider___0IuKc
                          )}
                        />
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__mvnDi
                        )}
                      >
                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__rLyj0
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__uP2UQ
                          )}
                        />

                        <Textinput
                          className={classNames(
                            "__wab_instance",
                            sty.textinput__vNBqJ
                          )}
                        />
                      </p.Stack>

                      <Button
                        children2={
                          <Icon5Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___5QEs
                            )}
                            role={"img"}
                          />
                        }
                        className={classNames(
                          "__wab_instance",
                          sty.button__xbXuk
                        )}
                        colors={"indigo"}
                        slot={"Start your account"}
                      />
                    </p.Stack>

                    <Divider
                      className={classNames(
                        "__wab_instance",
                        sty.divider___4Odz
                      )}
                    />

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__an3Nx)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___6AJ
                        )}
                      >
                        {
                          "A cras sagittis odio vestibulum pulvinar a eget hendrerit id vestibulum a leo sociosqu dictumst dictumst natoque magnis parturient."
                        }
                      </div>
                    </div>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          >
            <Navigation
              data-plasmic-name={"navigation"}
              data-plasmic-override={overrides.navigation}
              className={classNames("__wab_instance", sty.navigation)}
              hideCta={"hideCta"}
              slot={
                <React.Fragment>
                  <Button
                    className={classNames("__wab_instance", sty.button__nRuUs)}
                    link={"#services"}
                    navLink={"navLink"}
                    slot={"Services"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___67MHt)}
                    link={"#features"}
                    navLink={"navLink"}
                    slot={"Features"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button___5QR98)}
                    link={"#pricing"}
                    navLink={"navLink"}
                    slot={"Pricing"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__bnMon)}
                    link={"#testimonials"}
                    navLink={"navLink"}
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__t2GLa
                        )}
                      >
                        {"Testimonials"}
                      </div>
                    }
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__hi4Kf)}
                    navLink={"navLink"}
                    slot={"Log in"}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__aQu4H)}
                    darkGray={"darkGray"}
                    slot={"Sign up"}
                  />
                </React.Fragment>
              }
            >
              <img
                alt={""}
                className={classNames(defaultcss.img, sty.img__uoeyF)}
                role={"img"}
                src={image13FVFz0AkEbu1W6}
              />
            </Navigation>
          </HeroSection2>

          <div
            className={classNames(defaultcss.all, sty.freeBox__zRp35)}
            id={"services"}
          >
            <ValuesSection3
              data-plasmic-name={"valuesSection3"}
              data-plasmic-override={overrides.valuesSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___6AcIn)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__boc7O)}
                    >
                      <h2
                        data-plasmic-name={"h2"}
                        data-plasmic-override={overrides.h2}
                        className={classNames(
                          defaultcss.h2,
                          defaultcss.__wab_text,
                          sty.h2
                        )}
                      >
                        {"Proposing values"}
                      </h2>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___4LweN
                      )}
                    >
                      {
                        "Consectetur a adipiscing sagittis sed proin libero himenaeos ornare adipiscing suscipit leo vestibulum facilisi consequat nisi nisi adipiscing habitant facilisis suspendisse hac integer eget quam facilisis sem placerat fames."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox___597HY)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__klx8E)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__aE2Zu
                        )}
                        flat={"flat"}
                        slot={
                          "Nulla odio mauris enim parturient adipiscing vestibulum inceptos."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___3Wv1E
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Powerful"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__nsRvn
                        )}
                        flat={"flat"}
                        slot={
                          "Consequat scelerisque a eros taciti nisl a sodales."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__tk1W6
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Faster"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__tNcO
                        )}
                        flat={"flat"}
                        slot={"At ut condimentum amet adipiscing ac diam a."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__bvuTk
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Best and brightest"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__xsDAm
                        )}
                        flat={"flat"}
                        slot={
                          "Donec purus nec vestibulum volutpat vivamus vulputate suspendisse."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___7DGl
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__ec8Gf
                          )}
                        >
                          {"Dynamic range"}
                        </div>
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__pyl5A)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox___75F)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__zzba
                        )}
                        flat={"flat"}
                        slot={
                          "Commodo pretium himenaeos nisi potenti ad in ante."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__pKnh5
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__r2UuW
                          )}
                        >
                          {"Portable"}
                        </div>
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__rWkrH
                        )}
                        flat={"flat"}
                        slot={"Magna ullamcorper ut arcu nisi a per facilisis."}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__p70V3
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Production-ready"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__voN45
                        )}
                        flat={"flat"}
                        slot={
                          "Ac lobortis praesent sagittis dictumst fermentum vestibulum nunc."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__sRanX
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Magical"}
                      </Valueprop>

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop___1QGnl
                        )}
                        flat={"flat"}
                        slot={
                          "A parturient mi suspendisse nisl inceptos nullam a."
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__p0IxE
                            )}
                            role={"img"}
                          />
                        }
                      >
                        {"Accessible"}
                      </Valueprop>
                    </p.Stack>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.freeBox__xxjKl)}
            id={"features"}
          >
            <ValuesSection2Dark
              data-plasmic-name={"valuesSection2Dark"}
              data-plasmic-override={overrides.valuesSection2Dark}
            />
          </div>

          <div
            className={classNames(defaultcss.all, sty.freeBox__muRTe)}
            id={"pricing"}
          >
            <PricingSection3
              data-plasmic-name={"pricingSection3"}
              data-plasmic-override={overrides.pricingSection3}
              foreground={
                <React.Fragment>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__af8YD)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___7BfKp
                      )}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__gUiyL
                        )}
                      >
                        {"Pricing plans"}
                      </div>
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__r4Hg3
                      )}
                    >
                      {
                        "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                      }
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__hvoLz)}
                  >
                    <div
                      className={classNames(defaultcss.all, sty.freeBox__rBLa4)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__kdASt
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__fm7R0
                          )}
                        >
                          {"Starter"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__gyA8Y
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__tNtAn
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__s4DNt
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox___14EnO
                              )}
                            >
                              {"8"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__rL9HM
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__fcaVi
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__phJY
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__hSaow
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__mpWxm
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___2Jl3M
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___3CDyr
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__q8Gfx
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={"Mus consequat a justo"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__cdogL
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___3B2M1
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white"}
                          extraSmallShadow={"extraSmallShadow"}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__wmsl7
                              )}
                            >
                              {"Buy starter"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__nz90F)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__nAh7V
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__j0KHb
                          )}
                        >
                          {"Pro"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__ppBQs
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox___2BUch
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__goRLd
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__gIrw
                              )}
                            >
                              {"16"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__pHjVz
                            )}
                          >
                            {"/month"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider___4NqS0
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__vx3VC
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__ndDAq
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___4QTlU
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              "Ligula primis mollis sem dignissim semper lectus parturient"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___8HUX
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__aFgP
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__c690P
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.freeBox__kg22J
                                )}
                              >
                                {
                                  "A curabitur dignissim pharetra porta suscipit"
                                }
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__qrhYe
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__ghcdR
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__zIrn3
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              "Condimentum diam a et sapien praesent potenti torquent a eros"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__yxepf
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__rg6Ju
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__vBRru
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  defaultcss.__wab_text,
                                  sty.freeBox___8A7Rh
                                )}
                              >
                                {"Conubia in hac eu elementum sodales"}
                              </div>
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__sGAy9
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__qkZfH
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"green"}
                          extraSmallShadow={"extraSmallShadow"}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__q6Bz2
                              )}
                            >
                              {"Buy pro"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>

                    <div
                      className={classNames(defaultcss.all, sty.freeBox__zzFm9)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__dblOu
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__oBw4
                          )}
                        >
                          {"Team"}
                        </div>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__xVvrx
                          )}
                        >
                          <div
                            className={classNames(
                              defaultcss.all,
                              sty.freeBox__woGuk
                            )}
                          >
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__seid3
                              )}
                            >
                              {"$"}
                            </div>

                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox__mhTwR
                              )}
                            >
                              {"10"}
                            </div>
                          </div>

                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__pAaBd
                            )}
                          >
                            {"/member"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <Divider
                        className={classNames(
                          "__wab_instance",
                          sty.divider__edCT
                        )}
                      />

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__jIpOd
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            defaultcss.all,
                            sty.freeBox__s0RVl
                          )}
                        >
                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop__lArm6
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={"Ad nam curae a potenti platea"}
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg___2RBu9
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__a0P1X
                                )}
                                role={"img"}
                              />
                            }
                          />

                          <Valueprop
                            className={classNames(
                              "__wab_instance",
                              sty.valueprop___2CdiF
                            )}
                            flatIcon={"flatIcon"}
                            justDescription={"justDescription"}
                            slot={
                              "A adipiscing scelerisque pretium consectetur sem"
                            }
                            slot2={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__f7Eg7
                                )}
                                role={"img"}
                              />
                            }
                            slot22={
                              <Icon14Icon
                                className={classNames(
                                  defaultcss.all,
                                  sty.svg__mhVi4
                                )}
                                role={"img"}
                              />
                            }
                          />
                        </p.Stack>

                        <Button
                          colors={"white"}
                          extraSmallShadow={"extraSmallShadow"}
                          slot={
                            <div
                              className={classNames(
                                defaultcss.all,
                                defaultcss.__wab_text,
                                sty.freeBox___7Gar
                              )}
                            >
                              {"Buy team"}
                            </div>
                          }
                        />
                      </p.Stack>
                    </div>
                  </p.Stack>
                </React.Fragment>
              }
            />
          </div>

          <ShopBanners
            data-plasmic-name={"shopBanners"}
            data-plasmic-override={overrides.shopBanners}
            className={classNames("__wab_instance", sty.shopBanners)}
          >
            <Banner
              className={classNames("__wab_instance", sty.banner__zp0Qd)}
              left={
                <React.Fragment>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___8OMtH
                    )}
                  >
                    {"Sunglasses Collection"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__gk6Ok
                    )}
                  >
                    {"Get 25% off on selected items"}
                  </div>

                  <Button
                    slot={
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__kPVG
                        )}
                      >
                        {"Go to collection ->"}
                      </div>
                    }
                  />
                </React.Fragment>
              }
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox___1OiS)}
            >
              <Banner
                className={classNames("__wab_instance", sty.banner__qpPk1)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___3U9M
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___9AUuW
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__rmw
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__lVjGk)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1463100099107-aa0980c362e6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80"
                  }
                />
              </Banner>

              <Banner
                className={classNames("__wab_instance", sty.banner___6TZkD)}
                left={
                  <React.Fragment>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox___9IUrW
                      )}
                    >
                      {"Sunglasses Collection"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__sdY0N
                      )}
                    >
                      {"Get 25% off on selected items"}
                    </div>

                    <Button
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___4MOuH
                          )}
                        >
                          {"Go to collection ->"}
                        </div>
                      }
                    />
                  </React.Fragment>
                }
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__hiZ9L)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1554568218-0f1715e72254?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1834&q=80"
                  }
                />
              </Banner>
            </p.Stack>
          </ShopBanners>

          <LogoCloudSection2
            data-plasmic-name={"logoCloudSection2"}
            data-plasmic-override={overrides.logoCloudSection2}
            className={classNames("__wab_instance", sty.logoCloudSection2)}
          />

          <div
            className={classNames(defaultcss.all, sty.freeBox___1LLq4)}
            id={"testimonials"}
          >
            <TestimonialsSection1
              data-plasmic-name={"testimonialsSection1"}
              data-plasmic-override={overrides.testimonialsSection1}
            >
              <Testimonial
                className={classNames(
                  "__wab_instance",
                  sty.testimonial___8GLqn
                )}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__gKcI7)}
                    role={"img"}
                    src={
                      "https://www.caa.com/sites/default/files/styles/headshot_500x500/public/speaker-headshots/Morgan_CAAspeakers_Heashot_Web.jpg?itok=WCOhQ1Hj"
                    }
                  />
                }
              />

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__nv5IQ)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__b0Rh2)}
                    role={"img"}
                    src={
                      "https://tv-fanatic-res.cloudinary.com/iu/s--eXCbHIe1--/t_teaser_wide/cs_srgb,f_auto,fl_strip_profile.lossy,q_auto:420/v1371156342/elaine-benes-picture.png"
                    }
                  />
                }
                slot2={"Elaine Benes"}
                slot3={"Editor, Pendant Publishing"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__ooBe
                  )}
                >
                  {'"Vestibulum lacinia varius habitant dis aenean.'}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__p5HuH
                  )}
                >
                  {
                    'A parturient non ultricies a parturient leo a nascetur at consectetur turpis praesent mus ornare nulla posuere vel parturient."'
                  }
                </div>
              </Testimonial>

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__oNnzk)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__cJ7Gd)}
                    role={"img"}
                    src={
                      "https://i.pinimg.com/originals/87/d7/7d/87d77d68368fe5361d535b51cc5af09a.jpg"
                    }
                  />
                }
                slot2={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__pCtGc
                    )}
                  >
                    {"Woody Boyd"}
                  </div>
                }
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__oQWl
                    )}
                  >
                    {"Assistant Bartender, Cheers"}
                  </div>
                }
              >
                {
                  '"A ullamcorper etiam gravida a non maecenas ac parturient lectus vestibulum nam."'
                }
              </Testimonial>

              <Testimonial
                className={classNames("__wab_instance", sty.testimonial__jIzDo)}
                slot={
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__wjpQp)}
                    role={"img"}
                    src={
                      "https://a1cf74336522e87f135f-2f21ace9a6cf0052456644b80fa06d4f.ssl.cf2.rackcdn.com/images/characters_opt/p-fresh-randall-park.jpg"
                    }
                  />
                }
                slot2={"Louis Huang"}
                slot3={
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___2B4Q
                    )}
                  >
                    {"Restaurant Owner, Cattleman's Ranch"}
                  </div>
                }
              >
                {
                  '"Purus dis a primis rhoncus blandit velit suspendisse porta at ullamcorper suscipit a scelerisque sed pharetra facilisi vitae."'
                }
              </Testimonial>
            </TestimonialsSection1>
          </div>

          <CallToActionSection1
            data-plasmic-name={"callToActionSection1"}
            data-plasmic-override={overrides.callToActionSection1}
            className={classNames("__wab_instance", sty.callToActionSection1)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "heroSection2",
    "navigation",
    "valuesSection3",
    "h2",
    "valuesSection2Dark",
    "pricingSection3",
    "shopBanners",
    "logoCloudSection2",
    "testimonialsSection1",
    "callToActionSection1"
  ],

  heroSection2: ["heroSection2", "navigation"],
  navigation: ["navigation"],
  valuesSection3: ["valuesSection3", "h2"],
  h2: ["h2"],
  valuesSection2Dark: ["valuesSection2Dark"],
  pricingSection3: ["pricingSection3"],
  shopBanners: ["shopBanners"],
  logoCloudSection2: ["logoCloudSection2"],
  testimonialsSection1: ["testimonialsSection1"],
  callToActionSection1: ["callToActionSection1"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    heroSection2: makeNodeComponent("heroSection2"),
    navigation: makeNodeComponent("navigation"),
    valuesSection3: makeNodeComponent("valuesSection3"),
    h2: makeNodeComponent("h2"),
    valuesSection2Dark: makeNodeComponent("valuesSection2Dark"),
    pricingSection3: makeNodeComponent("pricingSection3"),
    shopBanners: makeNodeComponent("shopBanners"),
    logoCloudSection2: makeNodeComponent("logoCloudSection2"),
    testimonialsSection1: makeNodeComponent("testimonialsSection1"),
    callToActionSection1: makeNodeComponent("callToActionSection1"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
