// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fBsca94bet4EUSoXHGArJn
// Component: 7jlHC-LjyiARC
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Divider from "../../Divider"; // plasmic-import: pORI5sApnRrOD/component
import Valueprop from "../../Valueprop"; // plasmic-import: b5qPoGVcjzfiH/component
import Button from "../../Button"; // plasmic-import: lukbyibyAwqNS/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: fBsca94bet4EUSoXHGArJn/projectcss
import * as sty from "./PlasmicPricingSection3.module.css"; // plasmic-import: 7jlHC-LjyiARC/css
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: 5CFx7tW3uTLU2/icon

export const PlasmicPricingSection3__VariantProps = new Array();

export const PlasmicPricingSection3__ArgProps = new Array("foreground");

function PlasmicPricingSection3__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(defaultcss.all, sty.freeBox)}
      />

      <p.Stack
        as={"div"}
        data-plasmic-name={"foreground"}
        data-plasmic-override={overrides.foreground}
        hasGap={true}
        className={classNames(defaultcss.all, sty.foreground)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <React.Fragment>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox___3RUsv)}
              >
                <div className={classNames(defaultcss.all, sty.freeBox__mbpGs)}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox__n9BpD
                    )}
                  >
                    {"Pricing plans"}
                  </div>
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__nlW3N
                  )}
                >
                  {
                    "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                  }
                </div>
              </p.Stack>

              <div className={classNames(defaultcss.all, sty.freeBox___1K2H5)}>
                <div
                  className={classNames(defaultcss.all, sty.freeBox___6Xj08)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__knqGc)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__kHuAl
                      )}
                    >
                      {"Starter"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__hwa1I)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__ze1C4
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__lLxN0
                          )}
                        >
                          {"$"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__qfCqA
                          )}
                        >
                          {"8"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___66NO
                        )}
                      >
                        {"/month"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <Divider
                    className={classNames(
                      "__wab_instance",
                      sty.divider___0HqGh
                    )}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__ay93)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__lAiSm)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__lfTiZ
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          "Vestibulum mollis odio dictum ultrices facilisis molestie vestibulum"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__iRygX
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__daw4F
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__gbhnK
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={"Mus consequat a justo"}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__kwbt
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___59EVf
                            )}
                            role={"img"}
                          />
                        }
                      />
                    </p.Stack>

                    <Button
                      colors={"white"}
                      extraSmallShadow={"extraSmallShadow"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__hIyK
                          )}
                        >
                          {"Buy starter"}
                        </div>
                      }
                    />
                  </p.Stack>
                </div>

                <div className={classNames(defaultcss.all, sty.freeBox__xTDS)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__mcixo)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__lzcgV
                      )}
                    >
                      {"Pro"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        sty.freeBox___8YWnb
                      )}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__clJt7
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__t85Zm
                          )}
                        >
                          {"$"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__mKkce
                          )}
                        >
                          {"16"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox__eCcdO
                        )}
                      >
                        {"/month"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <Divider
                    className={classNames("__wab_instance", sty.divider__a8Nzp)}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__soCWo)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__kT3JJ)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__bLhY3
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          "Ligula primis mollis sem dignissim semper lectus parturient"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__eIBeT
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__oxIot
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__qM2Y8
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__evStV
                            )}
                          >
                            {"A curabitur dignissim pharetra porta suscipit"}
                          </div>
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__ixYrZ
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__pQq13
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__gNwH3
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          "Condimentum diam a et sapien praesent potenti torquent a eros"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__zLZhn
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__imwK
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__ef8Uj
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.freeBox__pzb8S
                            )}
                          >
                            {"Conubia in hac eu elementum sodales"}
                          </div>
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__gk1Ud
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__f2Syx
                            )}
                            role={"img"}
                          />
                        }
                      />
                    </p.Stack>

                    <Button
                      colors={"green"}
                      extraSmallShadow={"extraSmallShadow"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__lxCif
                          )}
                        >
                          {"Buy pro"}
                        </div>
                      }
                    />
                  </p.Stack>
                </div>

                <div className={classNames(defaultcss.all, sty.freeBox__sdUh0)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__ehSjo)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.freeBox__iz13F
                      )}
                    >
                      {"Team"}
                    </div>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__h71LS)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          sty.freeBox__jFr2Y
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox___14Hiz
                          )}
                        >
                          {"$"}
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__z6CQ
                          )}
                        >
                          {"10"}
                        </div>
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.freeBox___1GNns
                        )}
                      >
                        {"/member"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <Divider
                    className={classNames("__wab_instance", sty.divider__iyIKx)}
                  />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.freeBox__ixLpX)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.freeBox__sjysH)}
                    >
                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__kuz5D
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={"Ad nam curae a potenti platea"}
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__dc3Zu
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__pjQhW
                            )}
                            role={"img"}
                          />
                        }
                      />

                      <Valueprop
                        className={classNames(
                          "__wab_instance",
                          sty.valueprop__agskM
                        )}
                        flatIcon={"flatIcon"}
                        justDescription={"justDescription"}
                        slot={
                          "A adipiscing scelerisque pretium consectetur sem"
                        }
                        slot2={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__ls35O
                            )}
                            role={"img"}
                          />
                        }
                        slot22={
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__rgzBd
                            )}
                            role={"img"}
                          />
                        }
                      />
                    </p.Stack>

                    <Button
                      colors={"white"}
                      extraSmallShadow={"extraSmallShadow"}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.freeBox__zou4I
                          )}
                        >
                          {"Buy team"}
                        </div>
                      }
                    />
                  </p.Stack>
                </div>
              </div>
            </React.Fragment>
          ),

          value: args.foreground
        })}
      </p.Stack>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "foreground"],
  freeBox: ["freeBox"],
  foreground: ["foreground"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPricingSection3__ArgProps,
      internalVariantPropNames: PlasmicPricingSection3__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicPricingSection3__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPricingSection3";
  } else {
    func.displayName = `PlasmicPricingSection3.${nodeName}`;
  }
  return func;
}

export const PlasmicPricingSection3 = Object.assign(
  // Top-level PlasmicPricingSection3 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    foreground: makeNodeComponent("foreground"),
    // Metadata about props expected for PlasmicPricingSection3
    internalVariantProps: PlasmicPricingSection3__VariantProps,
    internalArgProps: PlasmicPricingSection3__ArgProps
  }
);

export default PlasmicPricingSection3;
/* prettier-ignore-end */
