// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fBsca94bet4EUSoXHGArJn
// Component: iwLFdIiajJGZ6
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Banner from "../../Banner"; // plasmic-import: rFx_o2QGdlilY/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_landing_page_starter.module.css"; // plasmic-import: fBsca94bet4EUSoXHGArJn/projectcss
import * as sty from "./PlasmicShopBanners.module.css"; // plasmic-import: iwLFdIiajJGZ6/css

export const PlasmicShopBanners__VariantProps = new Array();

export const PlasmicShopBanners__ArgProps = new Array("children");

function PlasmicShopBanners__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <React.Fragment>
            <Banner
              className={classNames("__wab_instance", sty.banner__u7Jb)}
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.freeBox__p9ITf)}
            >
              <Banner
                className={classNames("__wab_instance", sty.banner__f5D8M)}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__ftXRe)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1463100099107-aa0980c362e6?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80"
                  }
                />
              </Banner>

              <Banner
                className={classNames("__wab_instance", sty.banner___5Iz4H)}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__byBe3)}
                  role={"img"}
                  src={
                    "https://images.unsplash.com/photo-1554568218-0f1715e72254?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1834&q=80"
                  }
                />
              </Banner>
            </p.Stack>
          </React.Fragment>
        ),

        value: args.children
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicShopBanners__ArgProps,
      internalVariantPropNames: PlasmicShopBanners__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicShopBanners__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicShopBanners";
  } else {
    func.displayName = `PlasmicShopBanners.${nodeName}`;
  }
  return func;
}

export const PlasmicShopBanners = Object.assign(
  // Top-level PlasmicShopBanners renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicShopBanners
    internalVariantProps: PlasmicShopBanners__VariantProps,
    internalArgProps: PlasmicShopBanners__ArgProps
  }
);

export default PlasmicShopBanners;
/* prettier-ignore-end */
